name: Telegram Bot Worker

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install System Dependencies (UnRAR)
      run: |
        sudo apt-get update
        sudo apt-get install -y nmap

    - name: Install Python Requirements
      run: |
        pip install -r requirements.txt

    - name: Run Bot
      run: |
        python bot.py
